version: "3"
services:
  redis:
    image: "redis:alpine"
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '8000:8000'
  web:
    build: .
    restart: always
    container_name: 'demo_app_test'
    command: python main.py
    volumes:
      - .:/code
    ports:
      - '8000:8000'
  celery:
    build: .
    container_name: 'demo_app_celery'
    command: celery -A core worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis